const themes = [
  { id: "tinh_cach", name: "Tính cách" },
  { id: "so_thich", name: "Sở thích" },
  { id: "muc_tieu", name: "Mục tiêu" },
  { id: "giao_duc", name: "Học tập" },
  { id: "cong_viec", name: "Công việc" },
  { id: "tai_chinh", name: "Tài chính" },
  { id: "tinh_yeu", name: "Tình yêu" },
  { id: "tin_lanh", name: "Thuộc linh" },
  { id: "moi_quan_he", name: "Mối quan hệ" },
  { id: "suc_khoe", name: "Sức khỏe " },
];

const questionSets = {
  tinh_cach: [
    "Là người hướng nội real",
    "Là người hướng ngoại 100%",
    "Có tính kiên nhẫn 10đ",
    "Thường lắng nghe con tym",
    "Thích quyết định dựa trên logic",
    "Dễ bị căng thẳng khi gặp áp lực",
    "Có khả năng lãnh đạo",
    "Tự tin khi nói trước đám đông",
    "Thích sự ổn định hơn thay đổi",
    "Thường suy nghĩ kỹ trước khi hành động",
    "Thích làm việc một mình",
    "Linh hoạt thích nghi với môi trường mới",
    "Hay quan tâm đến cảm xúc người khác",
    "Dễ sáng tạo",
    "Thường đến sớm trong các cuộc hẹn",
    "Luôn giữ không gian sống ngăn nắp",
    "Ưu tiên hoàn thành công việc trước khi giải trí",
    "Thường hành động theo bản năng",
    "Dễ dàng phát hiện red flag trong giao tiếp",
    "Dễ tha thứ cho người khác",
    "Thận trọng khi đưa ra quyết định",
    "Chủ động giải quyết vấn đề",
    "Thích cạnh tranh trong công việc",
    "Luôn ưu tiên cho bản thân",
    "Hòa đồng dễ kết bạn mới",
  ],
  so_thich: [
    "Thích đọc sách",
    "Thích xem phim",
    "Thích nấu ăn",
    "Thích xem review phim",
    "Thích chơi thể thao",
    "Thích làm đồ thủ công",
    "Thích chơi nhạc cụ",
    "Thích chụp ảnh",
    "Thích viết blog hoặc nhật ký",
    "Thích vẽ tranh",
    "Thích nuôi thú cưng",
    "Thích chơi game",
    "Thích tập gym",
    "Thích làm vườn",
    "Thích khám phá ẩm thực mới",
    "Thích tham gia các hoạt động tình nguyện",
    "Thích sưu tầm đồ vật",
    "Thích học ngôn ngữ mới",
    "Thích ca hát",
    "Thích đi bộ",
    "Thích tiệc tùng",
    "Thích xem anime",
    "Thích xem thời sự",
    "Thích thức khuya",
    "Thích ngủ",
  ],
  muc_tieu: [
    "Muốn sở hữu nhà riêng trước 30 tuổi",
    "Đặt mục tiêu thăng tiến trong sự nghiệp",
    "Mong muốn có gia đình hạnh phúc",
    "Dự định du lịch khắp thế giới",
    "Muốn xây dựng sự nghiệp riêng",
    "Cố gắng sống lành mạnh hơn mỗi ngày",
    "Học hỏi kỹ năng mới mỗi năm",
    "Tham vọng đạt được thành công tài chính",
    "Muốn dành nhiều thời gian cho gia đình",
    "Dự định học cao học",
    "Đặt mục tiêu đọc 20 cuốn sách mỗi năm",
    "Muốn giúp đỡ người khác nhiều hơn",
    "Cố gắng sống cân bằng giữa công việc và cuộc sống",
    "Mong muốn tạo ảnh hưởng tích cực đến xã hội",
    "Muốn trở thành chuyên gia trong lĩnh vực",
    "Dự định nghỉ hưu sớm",
    "Muốn duy trì các mối quan hệ bạn bè lâu dài",
    "Đặt mục tiêu tiết kiệm một khoản lớn",
    "Muốn thành thạo một kỹ năng mới",
    "Dự định chuyển đến nơi ở lý tưởng",
    "Cố gắng sống gọn gàng",
    "Muốn hiểu rõ hơn về bản thân",
    "Mong muốn tìm được đam mê thực sự",
    "Đặt mục tiêu cải thiện sức khỏe tinh thần",
    "Muốn xây dựng thói quen tích cực",
  ],
  giao_duc: [
    "Đã tốt nghiệp đại học",
    "Học chuyên ngành yêu thích",
    "Tham gia các khóa học trực tuyến",
    "Từng học ở nước ngoài",
    "Thích học thêm ngoại ngữ",
    "Đọc sách chuyên ngành thường xuyên",
    "Tham gia các hội thảo học thuật",
    "Đã từng được học bổng",
    "Dành thời gian nghiên cứu sâu",
    "Thích chia sẻ kiến thức với người khác",
    "Tự học kỹ năng mới qua Internet",
    "Có chứng chỉ chuyên môn cao",
    "Tham gia câu lạc bộ học thuật",
    "Đã từng làm trợ giảng",
    "Thích học từ người có kinh nghiệm",
    "Có thói quen ghi chép khi học",
    "Đã tham gia nghiên cứu luận án",
    "Thường xuyên đọc báo khoa học",
    "Áp dụng kiến thức vào thực tế",
    "Theo dõi các khóa học trên YouTube",
    "Tham gia các dự án học tập nhóm",
    "Có kế hoạch học tập dài hạn",
    "Thích thảo luận học thuật",
    "Đã viết luận văn chuyên ngành",
    "Tích cực học hỏi từ đồng nghiệp",
  ],
  cong_viec: [
    "Làm việc trong lĩnh vực yêu thích",
    "Thường làm việc ngoài giờ",
    "Có mối quan hệ tốt với đồng nghiệp",
    "Chủ động đề xuất ý tưởng mới",
    "Ưu tiên môi trường làm việc thoải mái",
    "Thích công việc thách thức",
    "Đã từng chuyển đổi ngành nghề",
    "Làm việc từ xa nhiều thời gian",
    "Thường xuyên tham gia các dự án lớn",
    "Có kỹ năng quản lý thời gian tốt",
    "Thích làm việc trong môi trường năng động",
    "Đã từng làm việc tại startup",
    "Coi trọng cơ hội thăng tiến",
    "Có kỹ năng giao tiếp chuyên nghiệp",
    "Từng đảm nhiệm vị trí quản lý",
    "Ưu tiên công việc có ý nghĩa",
    "Làm việc hiệu quả dưới áp lực",
    "Đã từng tự kinh doanh",
    "Tham gia các khóa đào tạo công ty",
    "Thích làm việc theo dự án",
    "Cân bằng tốt giữa công việc và cuộc sống",
    "Hỗ trợ đồng nghiệp mới",
    "Luôn cập nhật xu hướng ngành",
    "Xây dựng mạng lưới quan hệ rộng",
    "Tìm kiếm cơ hội phát triển bản thân",
  ],
  tai_chinh: [
    "Lập kế hoạch tài chính hàng tháng",
    "Tiết kiệm một phần thu nhập",
    "Đầu tư vào chứng khoán",
    "Theo dõi chi tiêu cá nhân",
    "Có quỹ dự phòng khẩn cấp",
    "Tìm hiểu về đầu tư bất động sản",
    "Có mục tiêu tài chính dài hạn",
    "Tránh nợ tín dụng cao",
    "Sử dụng ứng dụng quản lý tài chính",
    "Đầu tư vào quỹ hưu trí",
    "Tìm hiểu về tiền điện tử",
    "Tự học về tài chính cá nhân",
    "Có nhiều nguồn thu nhập",
    "Không tiêu xài hoang phí",
    "Đã từng gặp khó khăn tài chính",
    "Thích tìm kiếm khuyến mãi",
    "So sánh giá trước khi mua sắm",
    "Có thói quen mua sắm có kế hoạch",
    "Đặt mục tiêu tự do tài chính",
    "Đã từng vay tiền mua nhà",
    "Đầu tư vào bản thân qua học tập",
    "Thận trọng khi chi tiêu lớn",
    "Chia sẻ chi phí chung với bạn đời",
    "Có bảo hiểm nhân thọ",
    "Lên kế hoạch tài chính cho tương lai",
  ],
  tinh_yeu: [
    "Coi trọng sự chân thành trong tình yêu",
    "Đang lên kế hoạch đám cưới",
    "Thích bất ngờ người yêu/bạn đời",
    "Ưu tiên chất lượng thời gian bên nhau",
    "Mong muốn gia đình nhỏ hạnh phúc",
    "Dành thời gian tìm hiểu trước hôn nhân",
    "Đã hẹn hò nhiều người",
    "Chuẩn bị tài chính trước khi cưới",
    "Thảo luận về kế hoạch tương lai với bạn đời",
    "Chia sẻ sở thích chung với người yêu",
    "Tôn trọng không gian riêng của đối phương",
    "Giải quyết mâu thuẫn bằng đối thoại",
    "Đã trải qua thất bại trong tình yêu",
    "Tin vào tình yêu đích thực",
    "Đặt gia đình lên hàng đầu",
    "Coi trọng sự đồng điệu trong tư tưởng",
    "Thích kỷ niệm các ngày đặc biệt",
    "Dành thời gian tìm hiểu gia đình đối phương",
    "Thường xuyên thể hiện tình cảm",
    "Lắng nghe ý kiến của đối phương",
    "Cùng nhau lập kế hoạch tài chính",
    "Đã quyết định số con mong muốn",
    "Đã tìm hiểu về nuôi dạy con cái",
    "Thống nhất phương pháp giáo dục con",
    "Đã thảo luận về cuộc sống hôn nhân",
  ],
  tin_lanh: [
    "Tham gia nhóm ban thanh niên",
    "Đọc Kinh Thánh hàng ngày",
    "Tham gia hát trong các dịp lễ",
    "Hầu việc trong các mục vụ",
    "Tham gia truyền giảng",
    "Cầu nguyện sáng thứ 7",
    "Tham gia các khóa học Kinh Thánh",
    "Tham gia nhóm nhỏ học Lời Chúa",
    "Dạy Trường Chúa Nhật cho các em",
    "Hỗ trợ công tác từ thiện của Hội Thánh",
    "Chia sẻ đức tin với bạn bè",
    "Tham gia các hoạt động thanh niên",
    "Tham gia trại hè",
    "Tham gia các buổi thờ phượng",
    "Trung tín trong phần mười",
    "Tham gia ban điều hành",
    "Hướng dẫn người mới tin Chúa",
    "Tham gia các chuyến truyền giáo",
    "Tổ chức các buổi cầu nguyện nhóm",
    "Học thuộc các câu Kinh Thánh",
    "Sống theo các nguyên tắc Cơ Đốc",
    "Tham gia các buổi nhóm thanh niên",
    "Chia sẻ chứng đạo cá nhân",
    "Hỗ trợ các hoạt động mục vụ",
    "Tham gia tổ chức các sự kiện Hội Thánh",
  ],
  moi_quan_he: [
    "Giữ liên lạc với bạn cũ",
    "Ưu tiên thời gian cho gia đình",
    "Xây dựng mạng lưới bạn bè đa dạng",
    "Tham gia các nhóm cộng đồng",
    "Tôn trọng ranh giới cá nhân",
    "Thẳng thắn trong giao tiếp",
    "Giúp đỡ người thân khi cần",
    "Tổ chức gặp mặt bạn bè thường xuyên",
    "Lắng nghe khi người khác chia sẻ",
    "Duy trì liên lạc với gia đình xa",
    "Giải quyết xung đột một cách hòa bình",
    "Thể hiện lòng biết ơn với người khác",
    "Tham gia các hoạt động nhóm",
    "Đặt ranh giới rõ ràng với đồng nghiệp",
    "Tôn trọng sự khác biệt văn hóa",
    "Hỗ trợ tinh thần cho bạn bè",
    "Dành thời gian riêng với từng người thân",
    "Giữ lời hứa với người khác",
    "Chia sẻ kinh nghiệm với người trẻ",
    "Học hỏi từ người lớn tuổi",
    "Giao tiếp cởi mở với cha mẹ",
    "Xây dựng niềm tin trong các mối quan hệ",
    "Hòa giải mâu thuẫn gia đình",
    "Tham gia các hoạt động cùng đồng nghiệp",
    "Duy trì mối quan hệ lâu dài",
  ],
  suc_khoe: [
    "Tập thể dục thường xuyên",
    "Ăn uống lành mạnh",
    "Ngủ đủ 7-8 tiếng mỗi ngày",
    "Uống đủ nước hàng ngày",
    "Thực hiện khám sức khỏe định kỳ",
    "Tránh thức khuya liên tục",
    "Hạn chế đồ ăn nhanh",
    "Tham gia các hoạt động ngoài trời",
    "Giảm thời gian sử dụng thiết bị điện tử",
    "Thực hành thiền hoặc yoga",
    "Chăm sóc sức khỏe tinh thần",
    "Duy trì cân nặng hợp lý",
    "Hạn chế đồ uống có cồn",
    "Không hút thuốc lá",
    "Rửa tay thường xuyên",
    "Cân bằng dinh dưỡng trong bữa ăn",
    "Nghỉ ngơi khi cơ thể mệt mỏi",
    "Trao đổi với bác sĩ khi có vấn đề",
    "Theo dõi chỉ số sức khỏe cá nhân",
    "Tham gia các môn thể thao yêu thích",
    "Duy trì thói quen vệ sinh cá nhân",
    "Tránh căng thẳng kéo dài",
    "Dành thời gian thư giãn",
    "Tìm hiểu về dinh dưỡng hợp lý",
    "Xây dựng lối sống tích cực",
  ],
};
