const themes = [
  { id: "so_thich", name: "Sở thích" },
  { id: "moi_quan_he", name: "Mối quan hệ" },
  { id: "suc_khoe", name: "Sức khỏe " },
  { id: "nang_khieu", name: "Năng khiếu " },
];

const questionSets = {
  so_thich: [
    "📚 Thích đọc sách",
    "🎬 Thích xem phim",
    "🍳 Thích nấu ăn",
    "🎥 Thích xem review phim",
    "⚽ Thích chơi thể thao",
    "🧶 Thích làm đồ thủ công",
    "🎸 Thích chơi nhạc cụ",
    "📸 Thích chụp ảnh",
    "📝 Thích viết blog hoặc nhật ký",
    "🎨 Thích vẽ tranh",
    "🐶 Thích nuôi thú cưng",
    "🎮 Thích chơi game",
    "💪 Thích tập gym",
    "🌱 Thích làm vườn",
    "🍽️ Thích khám phá ẩm thực mới",
    "🤝 Thích tham gia các hoạt động tình nguyện",
    "🧩 Thích sưu tầm đồ vật",
    "🗣️ Thích học ngôn ngữ mới",
    "🎤 Thích ca hát",
    "🚶‍♂️ Thích đi bộ",
    "🎉 Thích tiệc tùng",
    "🍣 Thích xem anime",
    "📰 Thích xem thời sự",
    "🌙 Thích thức khuya",
    "😴 Thích ngủ",
  ],
  moi_quan_he: [
    "🍳 Thích nấu ăn cùng mẹ",
    "👨‍🏫 Đã học được nhiều từ ba",
    "👧 Thường tâm sự với em gái",
    "🏡 Thích về quê thăm ông bà",
    "🤫 Có nhiều bí mật với mẹ",
    "👨‍👩‍👧‍👦 Có nhiều điểm chung với ba",
    "🛍️ Hay cùng mẹ đi chợ",
    "😇 Đang cố gắng làm ba mẹ vui",
    "🤐 Ít nói chuyện với ba",
    "💣 Bị áp lực từ gia đình",
    "🔒 Gia đình khá kiểm soát",
    "❤️ Có người yêu lâu năm",
    "😔 Đang cảm thấy cô đơn",
    "💻 Đã thử hẹn hò trực tuyến",
    "💔 Đã trải qua vài lần thất tình",
    "💖 Đã có một mối tình đẹp",
    "👫 Đã tìm được người ấy",
    "❤️‍🔥 Có người đặc biệt trong tim",
    "💍 Đang chờ đợi tình yêu đích thực",
    "🎮 Có người yêu cùng sở thích",
    "🏢 Có người yêu cùng nơi làm việc",
    "🌆 Có người yêu cùng quê",
    "🎂 Có người yêu hơn tuổi",
    "🎒 Có người yêu kém tuổi",
    "🙏 Có người yêu có cùng niềm tin",
  ],
  suc_khoe: [
    "🏋️‍♂️ Tập thể dục mỗi ngày",
    "🥦 Không thích rau xanh",
    "🍰 Thích ăn đồ ngọt",
    "🚶‍♀️ Đi bộ sau bữa ăn",
    "🧘‍♂️ Thư giãn đầu óc",
    "📚 Đọc sách về dinh dưỡng",
    "🏥 Khám sức khỏe định kỳ",
    "🍳 Tự nấu ăn tại nhà",
    "📵 Hạn chế dùng điện thoại",
    "🛏️ Đi ngủ sau 11 giờ",
    "🍵 Uống trà thảo mộc",
    "🍊 Ăn trái cây tươi",
    "🛁 Tắm nước ấm",
    "🌬️ Hít thở sâu",
    "🎶 Nghe nhạc thư giãn",
    "🧴 Chăm sóc da",
    "🏀 Chơi thể thao yêu thích",
    "🎉 Gặp gỡ bạn bè vui vẻ",
    "🥤 Uống nhiều nước có ga",
    "🏊‍♂️ Đi bơi mỗi tuần",
    "📚 Đọc sách về sức khỏe",
    "👨‍🍳 Học nấu ăn lành mạnh",
    "😴 Ngủ trưa ngắn",
    "🌳 Đi bộ công viên",
    "🎧 Nghe podcast sức khỏe",
    "🌱 Tự trồng rau sạch",
    "🍔 Thích ăn đồ ăn nhanh",
    "🧘‍♂️ Học cách quản lý stress",
    "🧑‍🦰 Dành thời gian cho bản thân",
    "📓 Viết nhật ký mỗi ngày",
    "🐾 Chơi với thú cưng",
    "💖 Học cách yêu bản thân",
    "🌞 Dùng kem chống nắng",
    "🥜 Ăn các loại hạt",
    "🚴‍♂️ Đi xe đạp mỗi ngày",
    "😂 Học cách cười nhiều hơn",
    "🌙 Thức khuya thường xuyên",
    "🛋️ Lười vận động",
    "🍟 Ăn nhiều đồ chiên rán",
    "🍳 Bỏ bữa sáng",
    "📱 Sử dụng điện thoại quá nhiều",
    "💺 Ngồi nhiều, ít vận động",
    "😓 Stress kéo dài",
    "🍬 Ăn quá nhiều đồ ngọt",
    "💊 Lạm dụng thuốc",
    "🚶‍♀️ Thiếu giao tiếp xã hội",
    "🌞 Không bảo vệ da khỏi ánh nắng",
    "⏳ Ăn quá nhanh",
    "🌙 Để bụng đói khi đi ngủ",
    "💺 Không thay đổi tư thế khi ngồi lâu",
  ],
  nang_khieu: [
    "👛 Biết làm đồ da",
    "🍶 Biết nặn gốm",
    "📄 Biết gấp giấy origami",
    "🕯️ Biết làm nến",
    "🧤 Biết làm đồ gỗ",
    "💌 Biết làm thiệp",
    "🌸 Biết làm hoa giấy",
    "💍 Biết làm trang sức",
    "🧵 Biết thêu tranh",
    "♻️ Biết làm đồ tái chế",
    "🧩 Biết lắp mô hình",
    "🐻 Biết may thú bông",
    "🏮 Biết làm lồng đèn",
    "🪁 Biết làm diều",
    "🐚 Biết trang trí bằng vỏ sò",
    "💎 Biết làm đồ cườm",
    "🧶 Biết móc len",
    "🌺 Biết trang trí hoa khô",
    "🎹 Biết chơi piano",
    "🎸 Biết chơi guitar",
    "🎻 Biết chơi violin",
    "🥁 Biết chơi trống",
    "🎵 Biết chơi sáo",
    "🎷 Biết chơi kèn",
    "🎼 Biết chơi ukulele",
    "🎹 Biết chơi organ",
    "🎸 Biết chơi bass",
    "🍹 Biết pha chế",
    "🍳 Biết nấu ăn",
    "🎂 Biết làm bánh kem",
    "🍕 Biết làm pizza",
    "🍦 Biết làm kem",
    "🍜 Biết làm phở bò",
    "🍊 Biết làm mứt Tết",
    "🍖 Biết làm kim chi",
    "🍝 Biết nấu mì Ý",
    "🍮 Biết làm bánh flan",
    "🍧 Biết làm chè",
    "🍶 Biết làm yaourt",
    "🏀 Chơi bóng rổ giỏi",
    "🏅 Từng đạt giải bơi lội",
    "⚽ Chơi bóng đá giỏi",
    "🏃‍♂️ Từng đạt giải chạy bộ",
    "🏐 Chơi bóng chuyền giỏi",
    "🏸 Từng đạt giải cầu lông",
    "🏓 Từng đạt giải bóng bàn",
    "🤾‍♂️ Chơi bóng ném giỏi",
    "🥏 Từng đạt giải ném đĩa",
    "🏓 Chơi bóng bàn giỏi",
    "🏆 Từng đạt giải bóng chuyền",
    "✍️ Có khả năng viết lách",
    "😂 Là người kể chuyện hài",
    "📝 Biết làm thơ",
    "🎙️ Biết làm MC",
    "🎨 Biết thiết kế",
    "💻 Biết lập trình",
    "🔲 Biết chơi rubik",
    "🎨 Biết vẽ tranh",
    "🔧 Biết sửa điện tử",
    "🎩 Biết làm ảo thuật",
    "♟️ Biết chơi cờ vua",
    "♞ Biết chơi cờ tướng",
    "🌻 Biết làm vườn",
    "💐 Biết cắm hoa",
    "📷 Biết chụp ảnh",
    "📹 Biết quay phim",
    "🎥 Biết làm video",
    "📢 Biết thuyết trình",
    "🌍 Biết nhiều ngoại ngữ",
    "💻 Biết cài win",
  ],
};
